name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGES.md'
      - 'LICENSE'
      - 'THANKS'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Copy gradle.properties
        run: cp gradle.properties.example gradle.properties
      - name: Build with Gradle
        run: ./gradlew build
      - name: Lint Check
        run: ./gradlew ktlintCheck

  slack_notify:
    needs: [build]
    runs-on: ubuntu-slim
    if: ${{ always() }}
    timeout-minutes: 5
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: sora-android-sdk
          slack_title: Build failed
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
